name: merge-pipeline.yml
#on:
#  pull_request:
#    branches:
#      - "main"
on:
  push:
    tags-ignore:
      - "*"
    branches-ignore:
      - "main"

jobs:
  push_to_backup:
    name: Push to backup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to backup repo
        uses: BarendNoordhoff/pipeline-projet-backup@main
        env:
          API_TOKEN_GITHUB: ${{ SECRETS.API_TOKEN_GITHUB }}
        with:
          source-directory: 'pipeline-project-backup'
          destination-github-username: 'barend'
          destination-repository-name: 'pipeline-project-backup'
          user-email: barendnoordhoff@hotmail.nl
          target-branch: main