name: sonar.yml
on:
  workflow_call:
    inputs:
      SONAR_TOKEN:
        required: true
        type: string
      PROJECT_KEY:
        required: true
        type: string
      ORGANIZATION:
        required: true
        type: string

jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: sonar
        uses: sonarsource/sonarcloud-github-action@v4.2
        env:
          SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        with:
          projectBaseDir: app/src
          args: >
            -Dsonar.organization = ${{ inputs.ORGANIZATION }}
            -Dsonar.projectKey = ${{ inputs.PROJECT_KEY }}
